
####################################
# エラー

# 以下、実行
# promptfoo redteam run

# 結果
# ↓ ↓ ↓
# Test Generation Report:
# ┌─────┬──────────┬────────────────────────────────────────┬────────────┬────────────┬──────────────┐
# │ #   │ Type     │ ID                                     │ Requested  │ Generated  │ Status       │
# ├─────┼──────────┼────────────────────────────────────────┼────────────┼────────────┼──────────────┤
# │ 1   │ Plugin   │ harmful:hate                           │ 5          │ 5          │ Success      │
# ├─────┼──────────┼────────────────────────────────────────┼────────────┼────────────┼──────────────┤
# │ 2   │ Strategy │ prompt-injection                       │ 5          │ 5          │ Success      │
# └─────┴──────────┴────────────────────────────────────────┴────────────┴────────────┴──────────────┘
# =================================================================================================================================
# Wrote 10 test cases to redteam.yaml
# =================================================================================================================================
# Running scan...
# You have exceeded the maximum cloud inference limit. Please contact inquiries@promptfoo.dev to upgrade your account.
####################################

# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: My Red Team Configuration
targets:
  - id: http
    config:
      url: http://127.0.0.1:8000/rag
      method: POST
      headers:
        Content-Type: application/json
      body: 
        question: '{{prompt}}'
    label: rag
prompts:
  - '{{prompt}}'
redteam:
  # purpose: |-
  #   The objective of the application is: sample

  #   You are: sample
  plugins:
    # - id: contracts  # Tests for unauthorized contractual commitments and legal exposure
    # - id: excessive-agency  # Tests for unauthorized actions beyond defined system boundaries
    # - id: hallucination  # Tests for fabrication of false or misleading information
    # - id: harmful:chemical-biological-weapons  # Tests handling of WMD-related content
    # - id: harmful:child-exploitation  # Tests handling of child exploitation content
    # - id: harmful:copyright-violations  # Tests handling of intellectual property violations
    # - id: harmful:cybercrime  # Tests handling of cybercrime-related content
    # - id: harmful:cybercrime:malicious-code  # Tests creation of malicious code
    # - id: harmful:graphic-content  # Tests handling of graphic or violent content
    # - id: harmful:harassment-bullying  # Tests handling of harassment and bullying content
    - id: harmful:hate  # Tests handling of hate speech and discriminatory content
    # - id: harmful:illegal-activities  # Tests handling of general illegal activities
    # - id: harmful:illegal-drugs  # Tests handling of illegal drug-related content
    # - id: harmful:illegal-drugs:meth  # Tests handling of methamphetamine-related content
    # - id: harmful:indiscriminate-weapons  # Tests handling of weapons-related content
    # - id: harmful:insults  # Tests handling of personal attacks and insults
    # - id: harmful:intellectual-property  # Tests handling of IP theft and violations
    # - id: harmful:misinformation-disinformation  # Tests handling of false information campaigns
    # - id: harmful:non-violent-crime  # Tests handling of non-violent criminal content
    # - id: harmful:privacy  # Tests handling of privacy violation attempts
    # - id: harmful:profanity  # Tests handling of profane or inappropriate language
    # - id: harmful:radicalization  # Tests handling of extremist content and recruitment
    # - id: harmful:self-harm  # Tests handling of self-harm and suicide content
    # - id: harmful:sex-crime  # Tests handling of sexual crime content
    # - id: harmful:sexual-content  # Tests handling of explicit sexual content
    # - id: harmful:specialized-advice  # Tests handling of unauthorized professional advice
    # - id: harmful:unsafe-practices  # Tests handling of dangerous activity instructions
    # - id: harmful:violent-crime  # Tests handling of violent crime content
    # - id: harmful:weapons:ied  # Tests handling of Improvised Explosive Devices
    # - id: hijacking  # Tests for unauthorized resource usage and purpose deviation
    # - id: pii:api-db  # Tests for PII exposure via API/database access
    # - id: pii:direct  # Tests for direct PII exposure vulnerabilities
    # - id: pii:session  # Tests for PII exposure in session data
    # - id: pii:social  # Tests for PII exposure via social engineering
    # - id: politics  # Tests handling of political content and bias
  strategies:
  # - id: basic  # Original plugin tests without any additional strategies or optimizations
  - id: prompt-injection
    config:
      sample: 1
# defaultTest:
#   options:
#     transformVars: '{ ...vars, sessionId: context.uuid }'
